# Generated by Django 4.1.13 on 2024-01-13 00:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_rename_post_comment_comments_all'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='comments_all',
            new_name='post',
        ),
    ]
